#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    DROP DATABASE IF EXISTS ${NAILGUN_DB:?};
    CREATE DATABASE ${NAILGUN_DB:?};
    DROP ROLE ${NAILGUN_DB_USER:?} IF EXISTS;
    CREATE ROLE ${NAILGUN_DB_USER:?} WITH LOGIN PASSWORD "${NAILGUN_DB_USERPW:?}";
EOSQL
