FROM selenium/standalone-firefox 2.53.1

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && \
    apt-get install --yes software-properties-common && \
    apt-get remove --yes nodejs nodejs-legacy && \
    add-apt-repository --yes ppa:chris-lea/node.js && \
    apt-get -y update && \
    apt-get -y dist-upgrade && \
    apt-get -y upgrade && \
    apt-get install --yes --reinstall libcanberra-gtk3-module \
    nodejs \
    python-software-properties \
    python-dev \
    python-pip \
    libjpeg-dev \
    x11-xserver-utils \
    wget \
    lsof \
    gksu \
    libcanberra-gtk-module \
    curl \
    alien \
    ruby-dev \
    createrepo \
    rpm \
    xvfb \
    gtk2-engines-pixbuf \
    xfonts-cyrillic \
    xfonts-100dpi \
    xfonts-75dpi \
    xfonts-base \
    xfonts-scalable\
    imagemagick \
    x11-apps \
    dpkg-dev

RUN pip install fuel-plugin-builder virtualenv virtualenvwrapper

RUN gem install fpm

ARG FUEL_WEB_PIP_REQS
RUN chmod +x /usr/local/bin/virtualenvwrapper.sh && \
    source /usr/local/bin/virtualenvwrapper.sh && \
    mkvirtualenv fuel-venv && \
    pip install --allow-all-external -r $FUEL_WEB_PIP_REQS && \
    pip install --upgrade python-fuelclient tox

ARG FUEL_UI_NPM_REQS
RUN npm install -g gulp && \
    wget --no-check-certificate -O package.json $FUEL_UI_NPM_REQS && \
    npm install
